# Generated by Django 3.0.4 on 2020-03-10 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moduleinfo',
            name='taughtBy',
        ),
    ]
