# Generated by Django 3.0.4 on 2020-03-10 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_remove_moduleinfo_taughtby'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduleinfo',
            name='taughtBy',
            field=models.ManyToManyField(to='modules.LecturerInfo'),
        ),
    ]
