# Generated by Django 3.0.4 on 2020-03-10 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0003_moduleinfo_taughtby'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
