# Generated by Django 3.0.4 on 2020-03-10 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0005_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleinfo',
            name='taughtBy',
            field=models.ManyToManyField(related_name='lecturerTeaching', to='modules.LecturerInfo'),
        ),
    ]
