# Generated by Django 3.0.4 on 2020-03-10 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0006_auto_20200310_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleinfo',
            name='taughtBy',
            field=models.ManyToManyField(to='modules.LecturerInfo'),
        ),
    ]
